SCT.Application.Web/Models/CarrinhoViewModel.cs
using SCT.Entity.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SCT.Application.Web.Models
{
    public class CarrinhoViewModel
    {
        public Carrinho Carrinho { get; set; }

        public string ReturnUrl { get; set; }
    }
}

SCT.Application.Web/Models/Paginacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SCT.Application.Web.Models
{
    public class Paginacao
    {
        public int ItensTotal { get; set; }
        public int ItensPorPagina { get; set; }
        public int PaginaAtual { get; set; }
        public int TotalPagina
        {
            get
            {
                return (int)Math.Ceiling((decimal)ItensTotal / ItensPorPagina);
            }
        }
    }
}

SCT.Application.Web/Models/ProdutoViewModel.cs
using SCT.Entity.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SCT.Application.Web.Models
{
    public class ProdutoViewModel
    {
        public IEnumerable<Produto> Produtos { get; set; }

        public Paginacao Paginacao { get; set; }

        public string CategoriaAtual { get; set; }
    }
}

SCT.Application.Web/Controllers/CarrinhoController.cs
using SCT.Application.Web.Models;
using SCT.Entity.Entidades;
using SCT.Entity.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCT.Application.Web.Controllers
{
    public class CarrinhoController : Controller
    {
        private ProdutosRepositorio _repositorio;
        //
        // GET: /Carrinho/
        public RedirectToRouteResult Adicionar(int produtoId, string returnUrl)
        {
            _repositorio = new ProdutosRepositorio();

            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                ObterCarrinho().AdicionarItem(produto, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        private Carrinho ObterCarrinho()
        {
            Carrinho carrinho = (Carrinho)Session["Carrinho"];

            if (carrinho == null)
            {
                carrinho = new Carrinho();
                Session["Carrinho"] = carrinho;
            }

            return carrinho;
        }

        public RedirectToRouteResult Remover(int produtoId, string returnUrl)
        {
            _repositorio = new ProdutosRepositorio();

            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                ObterCarrinho().RemoverItem(produto);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CarrinhoViewModel
            {
                Carrinho = ObterCarrinho(),
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Resumo()
        {
            Carrinho carrinho = ObterCarrinho();
            return PartialView(carrinho);
        }

        public ViewResult FecharPedido()
        {
            return View(new Pedido());
        }
    }
}

SCT.Application.Web/Controllers/CategoriaController.cs
using SCT.Entity.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCT.Application.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private ProdutosRepositorio _repositorio;
        //
        // GET: /Categoria/
        public PartialViewResult Menu(string categoria = null)
        {
            ViewBag.CategoriaSelecionada = categoria;

            _repositorio = new ProdutosRepositorio();

            IEnumerable<string> categorias = _repositorio.Produtos
                .Select(c => c.Categoria)
                .Distinct()
                .OrderBy(c => c);

            return PartialView(categorias);
        }
    }
}

SCT.Application.Web/Controllers/ProdutosController.cs
using SCT.Entity.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCT.Application.Web.Controllers
{
    public class ProdutosController : Controller
    {
        private ProdutosRepositorio _repositorio;

        //
        // GET: /Produtos/
        public ActionResult Index()
        {
            _repositorio = new ProdutosRepositorio();
            var produtos = _repositorio.Produtos.ToList();

            return View(produtos);
        }
    }
}

SCT.Application.Web/Controllers/VitrineController.cs
using SCT.Application.Web.Models;
using SCT.Entity.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCT.Application.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutosRepositorio _repositorio;
        public int ProdutoPorPagina = 8;

        //
        // GET: /Vitrine/
        public ViewResult ListProdutos(string categoria, int pagina = 1)
        {
            _repositorio = new ProdutosRepositorio();

            ProdutoViewModel model = new ProdutoViewModel
            {
                Produtos = _repositorio.Produtos
                    .Where(p => categoria == null || p.Categoria == categoria)
                    .OrderBy(p => p.Nome)
                    .Skip((pagina - 1) * ProdutoPorPagina)
                    .Take(ProdutoPorPagina),

                Paginacao = new Paginacao
                {
                    PaginaAtual = pagina,
                    ItensPorPagina = ProdutoPorPagina,
                    ItensTotal = _repositorio.Produtos.Count()
                },

                CategoriaAtual = categoria
            };

            return View(model);
        }
    }
}

SCT.Application.Web/Views/Carrinho/FecharPedido.cshtml
@model SCT.Entity.Entidades.Pedido

@{
    ViewBag.Title = "Seven: Fechar o pedido";
}

<h2>Fechamento Do Pedido</h2>

<p>Digite suas informações abaixo</p>

@using (Html.BeginForm())
{

    @Html.ValidationSummary()

    <h3>Enviar para</h3>

    <div class="form-group">
        <label>Nome do cliente:</label>
        @Html.TextBoxFor(x => x.NomeCliente, new { @class = "form-control" })
    </div>

    <h3>Dados para entrega</h3>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "NomeCliente" && property.PropertyName != "EmbrulhaPresente")
        {
            <div class="form-group">
                <label>
                    @(property.DisplayName ?? property.PropertyName)
                </label>

                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }

    <h3>Opções</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.EmbrulhaPresente, new { @class = "form-control" })
            Embrulha para presente?
        </label>
    </div>

    <input type="submit" class="btn btn-primary" value="Fechar o pedido" />
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script>
    $('#CEP').change(function (e) {
        e.preventDefault();

        $('#Endereco').val('');
        $('#Bairro').val('');
        $('#Cidade').val('');
        $('#Estado').val('');

        var cep = $('#CEP').val().replace("-", "");

        $.getJSON("http://cep.republicavirtual.com.br/web_cep.php?cep=" + cep + "&formato=json", {}, function (data) {
            if (data.resultado_txt == 'sucesso - cep completo') {
                $('#Endereco').val(data.tipo_logradouro + ' ' + data.logradouro);
                $('#Bairro').val(data.bairro);
                $('#Cidade').val(data.cidade);
                $('#Estado').val(data.uf);
            }
        });
    });
</script>

SCT.Application.Web/Views/Carrinho/Index.cshtml
@model SCT.Application.Web.Models.CarrinhoViewModel


<style>
    #carrinhoTable {
        vertical-align: middle;
    }
</style>

<h2>Seu Carrinho</h2>

<table id="carrinhoTable" class="table">
    <thead>
        <tr>
            <th class="text-center">Quantidade</th>
            <th class="text-center">Produto</th>
            <th class="text-right">Preço</th>
            <th class="text-right">SubTotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Carrinho.ItensCarrinho)
        {
            <tr>
                <td class="text-center">@item.Quantidade</td>
                <td class="text-center">@item.Produto.Nome</td>
                <td class="text-right">@item.Produto.Preco.ToString("c")</td>
                <td class="text-right">@((item.Quantidade * item.Produto.Preco).ToString("c"))</td>

                <td>
                    @using (Html.BeginForm("Remover", "Carrinho"))
                    {
                        @Html.Hidden("ProdutoId", item.Produto.ProdutoId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remover" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Carrinho.ObterValorTotal().ToString("c");
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">
        Continuar Comprando
    </a>

    @Html.ActionLink("Fechar o pedido", "FecharPedido", "Carrinho", new { @class = "btn btn-primary" })
</div>

SCT.Application.Web/Views/Carrinho/Resumo.cshtml
@model SCT.Entity.Entidades.Carrinho

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Carrinho", new { returnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Seus produtos:</b>
    @Model.ItensCarrinho.Sum(x => x.Quantidade) item(s), @Model.ObterValorTotal().ToString("c")
</div>

SCT.Application.Web/Views/Categoria/Menu.cshtml
@model System.Collections.Generic.IEnumerable<string>

@Html.ActionLink("Todos os produtos", "ListProdutos", "Vitrine", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Vitrine",
        action = "ListProdutos",
        categoria = link,
        pagina = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg"
        + (link == ViewBag.CategoriaSelecionada ? " btn-primary" : "")
    })
}

SCT.Application.Web/Views/Produtos/Index.cshtml
@model IEnumerable<SCT.Entity.Entidades.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProdutoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProdutoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProdutoId })
        </td>
    </tr>
}

</table>

SCT.Application.Web/Views/Shared/ProdutoDetalhes.cshtml
@model SCT.Entity.Entidades.Produto

<div class="well">
    <h3><strong>@Model.Nome</strong></h3>
    <h3><span class="pull-right label label-primary">@Model.Preco.ToString("c")</span></h3>

    @using (Html.BeginForm("Adicionar", "Carrinho"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProdutoId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Comprar" />
        </div>
    }

    <h3><span class="lead">@Model.Descricao</span></h3>
</div>

SCT.Application.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seven Cloth Technology</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>

    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Seven Cloth Technology</a>
        @Html.Action("Resumo", "Carrinho")
    </div>

    <div class="row panel">
        <div id="categorias" class="col-xs-2">
            @Html.Action("Menu", "Categoria")
        </div>

        <div id="categorias" class="col-xs-8">
            @RenderBody()
        </div>
    </div>


</body>
</html>

SCT.Application.Web/Views/Vitrine/ListProdutos.cshtml
@using SCT.Application.Web.HtmlHelpers

@model SCT.Application.Web.Models.ProdutoViewModel

@foreach (var p in Model.Produtos)
{
    @Html.Partial("ProdutoDetalhes", p)
}
<div class="btn-group">
    @Html.PageLinks(Model.Paginacao, x => Url.Action("ListProdutos", new { pagina = x, Model.CategoriaAtual  }))
</div>